# Generated by Django 2.0 on 2017-12-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='reply',
            new_name='text',
        ),
    ]
