# Generated by Django 2.0 on 2017-12-12 20:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20171213_0221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedback1',
        ),
    ]
