# Generated by Django 2.0 on 2017-12-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171213_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
