# Generated by Django 2.0 on 2017-12-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
